import React, {useMemo,useRef,useState} from 'react';

import {api} from './api.js';
import {parseCSV,transform,stats,exportCSV,SAMPLE,MAX_BYTES} from '../../../packages/core/index.js';
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const DATE_RE=/^\d{1,4}[/.-]\d{1,2}[/.-]\d{1,4}$/,NUM_RE=/^[+-]?[\d.,]+$/;
function colKind(rows,i){const v=rows.map(r=>(r[i]||'').trim()).filter(Boolean);if(!v.length)return 'text';if(v.every(x=>DATE_RE.test(x)))return 'date';if(v.every(x=>NUM_RE.test(x)&&/\d/.test(x)))return 'number';return 'text';}
export default function Cleaner({account,setRefresh}){
 const [text,setText]=useState(''),[delimiter,setDelimiter]=useState(','),[name,setName]=useState('untitled'),[error,setError]=useState(''),[options,setOptions]=useState({trimHeaders:false,removeBlank:false,removeDuplicates:false,formulaSafe:false,columns:{}}),[view,setView]=useState('original'),[page,setPage]=useState(0),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');const fileRef=useRef();const [saving,setSaving]=useState(false);
 async function saveRun(){setSaving(true);setMessage('');try{await api('/api/runs',{method:'POST',body:{name,delimiter,options,inputRows:parsed.rows.length,outputRows:result.rows.length,changeCount:result.log.length,log:result.log,csv:exportCSV(result,delimiter)}});setRefresh(n=>n+1);setMessage('Saved to your history.');}catch(e){setMessage(e.message);}finally{setSaving(false);}}
 const parsed=useMemo(()=>{if(!text)return null;try{return parseCSV(text,delimiter);}catch(e){return {failure:e.message};}},[text,delimiter]);
 const result=useMemo(()=>parsed&&!parsed.failure?transform(parsed,options):null,[parsed,options]);const diagnosis=parsed&&!parsed.failure?stats(parsed):null;
 function reset(source,filename){setText(source);setName(filename.replace(/\.csv$/i,''));setError('');setMessage('');setOptions({trimHeaders:false,removeBlank:false,removeDuplicates:false,formulaSafe:false,columns:{}});setView('original');setPage(0);setReviewed(false);}
 async function importFile(file){if(!file)return;try{if(file.size>MAX_BYTES)throw new Error('File exceeds 2 MB. Split it before importing.');const bytes=await file.arrayBuffer();const content=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(!content.trim())throw new Error('This file is empty. Choose another CSV or try the sample.');reset(content,file.name);}catch(e){setError(e.message.includes('encoded')?'This is not valid UTF-8. Save a UTF-8 CSV and try again.':e.message);}finally{if(fileRef.current)fileRef.current.value='';}}
 function update(key,value){setOptions(o=>({...o,[key]:value}));setReviewed(false);setMessage('');}
 const data=view==='cleaned'?result:parsed, rows=data?.rows||[],totalPages=Math.max(1,Math.ceil(rows.length/25)),visibleRows=rows.slice(page*25,page*25+25);
 function exportFile(){if(!result||result.errors.length||!reviewed)return;download(exportCSV(result,delimiter),`${name}-cleaned.csv`,'text/csv;charset=utf-8');setMessage('Cleaned CSV downloaded. Your original file is unchanged.');}
 return <><main><section className="hero"><div><div className="eyebrow">A LITTLE ORDER FOR MESSY DATA</div><h1>Messy export.<br/><span>Clean start.</span></h1><p>Preview your CSV, choose the fixes, and export a clean copy.<br className="desktop"/> Cleaning stays in your browser. Sign in to save your runs.</p></div><svg className="ecg" viewBox="0 0 600 80" aria-hidden="true" preserveAspectRatio="none"><path d="M0 40 H170 L195 40 L215 8 L245 72 L270 40 H360 L380 40 L398 22 L418 58 L436 40 H600"/></svg><div className="hero-note"><span>01 / INSPECT</span><span>02 / CHOOSE FIXES</span><span>03 / EXPORT</span><div className="note-line"/></div></section>
 <section className="import-card"><div><h2>Start with your CSV</h2><p>UTF-8 · up to 2 MB · 10,000 rows · explicit delimiter</p></div><div className="import-actions"><input ref={fileRef} type="file" accept=".csv,text/csv,text/plain" aria-label="Choose CSV file" onChange={e=>importFile(e.target.files[0])}/><button className="primary" onClick={()=>fileRef.current.click()}>↥ Choose CSV</button><button onClick={()=>reset(SAMPLE,'sample-orders.csv')}>Try sales sample</button></div></section>
 <details className="paste"><summary>Or paste CSV text</summary><textarea aria-label="CSV input" rows="6" value={text} placeholder="Order,Date,Amount…" onChange={e=>{reset(e.target.value,name);}}/><p>Pasted input is not uploaded. Only runs you choose to save are stored.</p></details>
 <div className="delimiter"><label htmlFor="delimiter">Delimiter</label><select id="delimiter" value={delimiter} onChange={e=>{setDelimiter(e.target.value);setPage(0);setReviewed(false);}}><option value=",">Comma (,)</option><option value=";">Semicolon (;)</option><option value={'\t'}>Tab</option><option value="|">Pipe (|)</option></select><span>Choose the separator used by your export.</span></div>
 {(error||parsed?.failure)&&<div role="alert" className="error">{error||parsed.failure}</div>}
 {!result&&<section className="empty"><span className="empty-icon">▦</span><h2>A safer way to tidy spreadsheets</h2><p>Spot broken rows, remove exact duplicates, and choose date or number formats.<br/>Nothing changes until you select it. The sample is synthetic, so you can explore freely.</p><div className="pills"><span>Original preserved</span><span>No telemetry</span><span>Formula-safe export</span></div></section>}
 {result&&<><section className="stats" aria-label="CSV diagnostics">{[[parsed.rows.length,'Input rows'],[parsed.headers.length,'Columns'],[diagnosis.blanks,'Blank rows'],[diagnosis.duplicates,'Exact duplicates'],[result.errors.length,'Errors to resolve']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
 <div className="workspace"><aside className="fixes"><div className="section-label">YOUR CLEANUP RECIPE</div><h2>Choose, don't guess.</h2><p>All fixes are off until you select them.</p>{[['trimHeaders','Trim header whitespace',`${diagnosis.headers} headers with extra spaces`],['removeBlank','Remove blank rows',`${diagnosis.blanks} rows with no values`],['removeDuplicates','Remove exact duplicates',`${diagnosis.duplicates} repeated rows; keep the first`],['formulaSafe','Protect spreadsheet formulas',"Prefixes risky cells and headers with an apostrophe, including negative numbers. This changes the data."]].map(([key,label,detail])=><label className="check" key={key}><input type="checkbox" checked={options[key]} onChange={e=>update(key,e.target.checked)}/><span><b>{label}</b><small>{detail}</small></span></label>)}
 <div className="format-title">Column formats <span>optional</span></div><p>Ambiguous dates are never inferred. Choose the source format, or keep values unchanged.</p>{parsed.headers.map((h,i)=><label className="column-rule" key={i}><span>{h||`Column ${i+1}`}{colKind(parsed.rows,i)==='text'&&<em style={{fontStyle:"normal",opacity:.6,fontSize:".8em"}}> text, nothing to format</em>}</span><select disabled={colKind(parsed.rows,i)==='text'} aria-label={`Format for column ${i+1}: ${h}`} value={options.columns[i]||''} onChange={e=>update('columns',{...options.columns,[i]:e.target.value})}><option value="">Keep unchanged</option>{colKind(parsed.rows,i)!=='number'&&colKind(parsed.rows,i)!=='text'&&<>{[['date:dmy','Date: DD/MM/YYYY → ISO'],['date:mdy','Date: MM/DD/YYYY → ISO'],['date:ymd','Date: YYYY-MM-DD → ISO']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</>}{colKind(parsed.rows,i)!=='date'&&colKind(parsed.rows,i)!=='text'&&<>{[['number:us','Number: 1,234.56 → 1234.56'],['number:eu','Number: 1.234,56 → 1234.56']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</>}</select></label>)}</aside>
 <section className="preview"><div className="preview-head"><div><div className="section-label">{name}.csv</div><h2>See the difference.</h2></div><div className="tabs" role="group" aria-label="Preview version"><button aria-pressed={view==='original'} className={view==='original'?'active':''} onClick={()=>{setView('original');setPage(0);}}>Original</button><button aria-pressed={view==='cleaned'} className={view==='cleaned'?'active':''} onClick={()=>{setView('cleaned');setPage(0);}}>Cleaned</button></div></div>
 {result.errors.length>0&&<div className="error" role="alert"><b>Export paused: {result.errors.length} errors to resolve</b><ul>{result.errors.slice(0,20).map((e,i)=><li key={i}>Row {e.row}{e.column?`, column ${e.column}`:''}: {e.message}</li>)}</ul>{result.errors.length>20&&<p>Showing the first 20 errors.</p>}<p>Edit the pasted source or fix the original file and import again.</p></div>}
 <div className="table-wrap" tabIndex="0" role="region" aria-label="CSV preview, scroll horizontally for more columns"><table><thead><tr><th scope="col">#</th>{data.headers.map((h,i)=><th scope="col" key={i}>{h||'(empty header)'}</th>)}</tr></thead><tbody>{visibleRows.map((r,i)=><tr key={i}><th scope="row">{page*25+i+1}</th>{r.map((v,j)=><td key={j}>{v||<span className="muted">empty</span>}</td>)}</tr>)}</tbody></table></div><div className="pagination"><span>{rows.length} {view==='cleaned'?'output':'input'} rows · page {page+1} / {totalPages}</span><div><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Previous</button><button disabled={page+1>=totalPages} onClick={()=>setPage(p=>p+1)}>Next →</button></div></div>
 <div className="changes"><h3>Change log <span>{result.log.length} changes</span></h3>{!result.log.length?<p>No changes selected. Your data is preserved as-is.</p>:<ol>{result.log.slice(0,12).map((l,i)=><li key={i}><b>{l.action}</b><span>Source row {l.row}{l.column?` · column ${l.column}`:''}</span>{l.after!==null&&<code>{JSON.stringify(l.before)} → {JSON.stringify(l.after)}</code>}</li>)}</ol>}{result.log.length>12&&<p>Previewing 12 of {result.log.length} changes. Download the full log below.</p>}</div>
 <div className="export"><label className="check"><input type="checkbox" checked={reviewed} disabled={result.errors.length>0} onChange={e=>setReviewed(e.target.checked)}/><span><b>I reviewed the cleaned preview and selected changes.</b><small>Check date/number interpretation before using your export.</small></span></label><div className="export-actions"><button className="primary" disabled={!reviewed||result.errors.length>0} onClick={exportFile}>↓ Export cleaned CSV</button><button disabled={!reviewed||result.errors.length>0} onClick={()=>download(JSON.stringify({file:name,delimiter,options,inputRows:parsed.rows.length,outputRows:result.rows.length,changes:result.log},null,2),`${name}-changes.json`,'application/json')}>↓ Change log (JSON)</button>{account.email&&<button disabled={!reviewed||result.errors.length>0||saving} onClick={saveRun}>{saving?'Saving…':'☁ Save to my history'}</button>}</div><p role="status">{message||'Export never overwrites the original. Formula protection is an opt-in transform, not a guarantee for every spreadsheet app.'}</p></div></section></div></>}
 </main><footer><span>CSV Doctor · Built for everyday exports.</span><span>Cleaning is local. Saved runs are stored only if you sign in and save.</span></footer></>;
}
