import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseCSV,transform,exportCSV,dateValue,numberValue,MAX_BYTES,SAMPLE,stats} from './index.js';
test('quoted commas, escaped quotes and multiline cells roundtrip',()=>{const text='A,B\n"one, two","say ""hi""\nnext"';const d=parseCSV(text);assert.deepEqual(d.rows,[['one, two','say "hi"\nnext']]);assert.deepEqual(parseCSV(exportCSV(d)).rows,d.rows);});
test('BOM and semicolon delimiter',()=>assert.deepEqual(parseCSV('\uFEFFA;B\n1;2',';').headers,['A','B']));
test('empty file explains error',()=>assert.throws(()=>parseCSV(''),/empty/));
test('oversized input rejected',()=>assert.throws(()=>parseCSV('a'.repeat(MAX_BYTES+1)),/2 MB/));
test('row count limit',()=>assert.throws(()=>parseCSV('A\n'+'x\n'.repeat(10001)),/10,000/));
test('broken rows and unclosed quotes block export',()=>{for(const input of ['A,B\n1','A,B\n"broken,2'])assert.throws(()=>exportCSV(transform(parseCSV(input))),/Resolve/);});
test('header collisions list column numbers',()=>{const t=transform(parseCSV(' A ,A\n1,2'),{trimHeaders:true});assert.match(t.errors[0].message,/columns 1 and 2/);});
test('blank headers block export',()=>assert.equal(transform(parseCSV('A,\n1,2')).errors.length,1));
test('nothing changes by default, original remains intact',()=>{const d=parseCSV(SAMPLE),original=JSON.stringify(d);const t=transform(d);assert.deepEqual(t.rows,d.rows);assert.equal(t.log.length,0);transform(d,{trimHeaders:true,removeBlank:true,removeDuplicates:true});assert.equal(JSON.stringify(d),original);});
test('selected cleanup removes only exact duplicates and blanks',()=>{const t=transform(parseCSV(SAMPLE),{trimHeaders:true,removeBlank:true,removeDuplicates:true});assert.equal(t.rows.length,4);assert.equal(t.log.length,3);});
test('sample diagnostics',()=>assert.deepEqual(stats(parseCSV(SAMPLE)),{duplicates:1,blanks:1,formulas:1,headers:1}));
test('date interpretation explicit and calendar-valid',()=>{assert.equal(dateValue('01/02/2026','dmy'),'2026-02-01');assert.equal(dateValue('01/02/2026','mdy'),'2026-01-02');assert.equal(dateValue('29/02/2026','dmy'),null);assert.equal(dateValue('29/02/2024','dmy'),'2024-02-29');assert.equal(dateValue('2026-13-01','ymd'),null);});
test('numbers explicit and strict without precision loss',()=>{assert.equal(numberValue('1,234.50','us'),'1234.50');assert.equal(numberValue('1.234,50','eu'),'1234.50');assert.equal(numberValue('12,34','us'),null);assert.equal(numberValue('9007199254740993','us'),'9007199254740993');});
test('invalid selected format blocks export and preserves value',()=>{const t=transform(parseCSV('Date\n31/02/2026'),{columns:{0:'date:dmy'}});assert.equal(t.rows[0][0],'31/02/2026');assert.equal(t.errors[0].row,2);assert.throws(()=>exportCSV(t));});
test('formula protection includes headers, whitespace and all trigger types',()=>{const d=parseCSV('=HEADER,B\n  =SUM(1),+12\n@X,-1\n"\tX",safe');const t=transform(d,{formulaSafe:true});assert.equal(t.headers[0],"'=HEADER");assert.equal(t.rows[0][0],"'  =SUM(1)");assert.equal(t.rows[1][1],"'-1");assert.equal(t.log.length,6);assert.equal(d.headers[0],'=HEADER');});
test('selected formats produce auditable output',()=>{const t=transform(parseCSV('Date,Amount\n01/02/2026,"1,000.00"'),{columns:{0:'date:dmy',1:'number:us'}});assert.deepEqual(t.rows,[['2026-02-01','1000.00']]);assert.equal(t.log.length,2);});
